algoritmo "média anual"
// Função :
// Autor :
// Data : 10/01/2019
// Seção de Declarações 
var
nome: caractere
n1,n2,n3,n4,media: real
inicio
escreval ("digite o nome do aluno ")
leia (nome)
escreval ("digite 1ª nota")
leia (n1)
escreval ("digite 2ª nota")
leia(n2)
escreval ("digite 3ª nota")
leia (n3)
escreval ("digite 4ª nota")
leia (n4)
media<-(n1+n2+n3+n4)/4
escreval("média anual do aluno:",nome, " é " ,media)
// Seção de Comandos 
fimalgoritmo
