algoritmo "semnome"
// Função :
// Autor :
// Data : 25/03/2019
// Seção de Declarações 
var
A,B,C,X1,X2,D: real
inicio
escreval("digite valor de A")
leia(A)
escreval("digite valor de B")
leia(B)
escreval("digite valor de C")
leia(C)
D<-((B^2)-4*A*C)
escreval("delta é igual a" ,D)
escreval("agora vamos ver o valor de X1 e X2")
X1<-(-B+RaizQ(D))/2*A
escreval("o valor de X1 é" ,X1)
X2<-(-b-RaizQ(D))/2*A
escreval("o valor de X2 é" ,X2)
// Seção de Comandos 
fimalgoritmo
