algoritmo "semnome"
// Função :
// Autor :
// Data : 25/03/2019
// Seção de Declarações 
var
NQ,ND,NC,RQ,RC: real
inicio
escreval(" digite um numero positivo e maior que 0")
leia(ND)
NQ<-ND^2
escreval("o valor do numero elevado ao quadrado é", NQ)
NC<-ND^3
escreval("o valor desse numero elevado ao cubo é" ,NC)
RQ<-RaizQ(ND)
escreval("o valor desse numero na raiz quadrada é" ,RQ)
RC<-ND/3/3/3
escreval("o valor desse numero na raiz cubica é" ,RC)
// Seção de Comandos 
fimalgoritmo
